### ISSUE TITLE
Split Base64 Benchmarks to their own Benchmark test file.

### ISSUE THREAD

**Issue by MakoEnergy** [BlackToppStudios/Mezz_Foundation#61]
Currently we are comparing our own implementation of Base64 encoding and the original implementation it is based on in the same file as the rest of the Base64 tests.  As it is a benchmark, it should be separated into it's own Benchmark file.

Additionally, we should switch to using the newer MicroBenchmark utilities in Mezz_Test where applicable.

**Comment by Sqeaky** [comment]
I did this in the last PR
